### ISSUE TITLE
[BUG] navbar jumping when scrolling

### ISSUE THREAD

**Issue by RobertRR11** [Compliance-Resource-Pack/Website#23]
**Describe the bug**
When opening a page and you start scrolling down, the navbar just jumps to the top instead of transitioning or always following the top. I've tried to fix it myself but our css is really scuffed ngl

**To Reproduce**
1. open any page
2. scroll down
3. navbar doing weird jump / no transition

**Comment by Juknum** [comment]
Can you post a video about it? I can't reproduce it on my side :/

**Comment by RobertRR11** [comment]
> Can you post a video about it? I can't reproduce it on my side :/

https://user-images.githubusercontent.com/57044042/140503748-cc5c125a-fa33-4d39-aa19-98e9625869f0.mp4

**Comment by Juknum** [comment]
Oh, I don't really now if we can easily fix that

**Comment by RobertRR11** [comment]
Actually I kinda managed to find a possible fix, by having the header element the same height as the navbar. But the problem with that is, that of mobile devices, where the navbar behaves different, the height somehow would need to be dynamically changed with the navbar expanding
