### ISSUE TITLE
Optimize for mobile screen size

### ISSUE THREAD

**Issue by Juknum** [Compliance-Resource-Pack/Website#28]

**Comment by RobertRR11** [comment]
The last big mobile issue is the downloads page, which could be resolved by either stripping the date and size properties at a specific screen width or by displaying a warning to turn your phone sideways when the screen width is too small

**Comment by TheRolfFR** [comment]
What a **** in the *** to work on the download code berk, but I successfully managed to do what I wanted after 3h30 of work :
![image](https://user-images.githubusercontent.com/18086786/151815540-203e4703-32a0-4310-baef-7248a527444b.png)
No change in desktop, I added as few lines of code as possible.
But I have a great result with no data compromise.
Tell me what you think, I didn't push yet

**Comment by RobertRR11** [comment]
wow looks great

**Comment by Juknum** [comment]
That's a big yes

**Comment by RobertRR11** [comment]
Closing this now due to all known mobile issues being resolved
