### ISSUE TITLE
Add Afrikaans Website Translation

### ISSUE THREAD

**Issue by UnicornXP** [Compliance-Resource-Pack/Website#41]
I'd like an Afrikaans version of the website, please.

**Comment by shaunroselt** [comment]
Pull Request for Afrikaans Language Support 😁 

https://github.com/Compliance-Resource-Pack/Website/pull/42

![image](https://user-images.githubusercontent.com/5418178/150214111-9d90ceac-739f-466c-bade-a6f3be0f1029.png)
